name: Build rocky9 and Compile Nginx with Module

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          yum install -y sudo
          sudo yum install -y git gcc patch diffutils autoconf automake \
          zlib-devel pcre2-devel make libtool

      # Download Nginx source code
      - name: Download Nginx source
        run: |
          pwd 
          ls -lhat 
          cd ..
          git clone https://github.com/nginx/nginx.git
      
      # download libressl ssl
      - name: Download libressl ssl
        run: |
          pwd 
          ls -lhat 
          cd ..
          git clone https://github.com/libressl/portable.git
          cd portable
          ./autogen.sh

      # download nginx-module-vts
      - name: Download nginx-module-vts
        run: |
          cd ..
          git clone https://github.com/vozlt/nginx-module-vts.git


      # Configure and compile Nginx with the dynamic module
      - name: Configure and build Nginx with module
        run: |
          pwd 
          ls -lhat 
          cd ../nginx
          auto/configure --prefix=/usr/local/nginx --with-compat --with-http_v2_module \
          --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module \
          --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module \
          --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module \
          --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module \
          --with-http_v3_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module \
          --with-stream_ssl_preread_module \
          --with-openssl=../portable \
          --add-module=../brutal-nginx \
          --add-module=../nginx-module-vts 
          make -j
          sudo make install

      # Verify the Nginx installation
      - name: Verify Nginx version
        run: /usr/local/nginx/sbin/nginx -v
      # show logs
      - name: Show Nginx logs
        run: |
          sudo /usr/local/nginx/sbin/nginx -p  /usr/local/nginx -c conf/nginx.conf
          sudo cat /usr/local/nginx/logs/error.log

      # Package the build (optional)
      - name: Package Nginx binary
        run: |
          cd /usr/local/nginx
          filename=nginx-built-rocky9.tar.gz
          sudo tar -czvf $filename sbin/ conf/ html/ logs/
          sudo mv $filename $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          sudo chown runner:runner $filename  # Change ownership to runner
          ls -lhat $GITHUB_WORKSPACE
          pwd

      # Upload the package as an artifact (optional)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-built
          path: nginx-built-rocky9.tar.gz
